// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tiefebot.Data;

#nullable disable

namespace tiefebot.Migrations
{
    [DbContext(typeof(DataBase))]
    [Migration("20250309161009_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("tiefebot.Data.Entity.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("PlayerDiscordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("tiefebot.Data.Entity.CharacterInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.ToTable("CharacterInventories");
                });

            modelBuilder.Entity("tiefebot.Data.Entity.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterInventoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterInventoryId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("tiefebot.Data.Entity.noeItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("noeItems");
                });

            modelBuilder.Entity("tiefebot.Data.Entity.CharacterInventory", b =>
                {
                    b.HasOne("tiefebot.Data.Entity.Character", "Character")
                        .WithOne("CharacterInventory")
                        .HasForeignKey("tiefebot.Data.Entity.CharacterInventory", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("tiefebot.Data.Entity.Item", b =>
                {
                    b.HasOne("tiefebot.Data.Entity.CharacterInventory", "CharacterInventory")
                        .WithMany("Items")
                        .HasForeignKey("CharacterInventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterInventory");
                });

            modelBuilder.Entity("tiefebot.Data.Entity.Character", b =>
                {
                    b.Navigation("CharacterInventory")
                        .IsRequired();
                });

            modelBuilder.Entity("tiefebot.Data.Entity.CharacterInventory", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
