// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tiefebot.Data;

#nullable disable

namespace tiefebot.Migrations
{
    [DbContext(typeof(DataBase))]
    partial class DataBaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("tiefebot.Data.Entity.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Armor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Combat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dexterity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Empathy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intelligent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("MemberDiscordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Personality")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("tiefebot.Data.Entity.InvItem", b =>
                {
                    b.Property<Guid>("InventoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ammunition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Durability")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("InventoryId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("InvItems");
                });

            modelBuilder.Entity("tiefebot.Data.Entity.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("tiefebot.Data.Entity.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Damage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDisposable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxStack")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasDiscriminator<int>("ItemType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("tiefebot.Data.Entity.Ammo", b =>
                {
                    b.HasBaseType("tiefebot.Data.Entity.Item");

                    b.Property<int>("AmmoType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMagazine")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("tiefebot.Data.Entity.Defence", b =>
                {
                    b.HasBaseType("tiefebot.Data.Entity.Item");

                    b.Property<bool>("IsWearable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Protection")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("tiefebot.Data.Entity.Medication", b =>
                {
                    b.HasBaseType("tiefebot.Data.Entity.Item");

                    b.Property<int>("Heal")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("tiefebot.Data.Entity.Tool", b =>
                {
                    b.HasBaseType("tiefebot.Data.Entity.Item");

                    b.Property<string>("Usage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("tiefebot.Data.Entity.Weapon", b =>
                {
                    b.HasBaseType("tiefebot.Data.Entity.Item");

                    b.Property<int>("ROF")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeaponType")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("tiefebot.Data.Entity.InvItem", b =>
                {
                    b.HasOne("tiefebot.Data.Entity.Inventory", "Inventory")
                        .WithMany("InvItems")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tiefebot.Data.Entity.Item", "Item")
                        .WithMany("InvItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("tiefebot.Data.Entity.Inventory", b =>
                {
                    b.HasOne("tiefebot.Data.Entity.Character", "Character")
                        .WithOne("Inventory")
                        .HasForeignKey("tiefebot.Data.Entity.Inventory", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("tiefebot.Data.Entity.Character", b =>
                {
                    b.Navigation("Inventory")
                        .IsRequired();
                });

            modelBuilder.Entity("tiefebot.Data.Entity.Inventory", b =>
                {
                    b.Navigation("InvItems");
                });

            modelBuilder.Entity("tiefebot.Data.Entity.Item", b =>
                {
                    b.Navigation("InvItems");
                });
#pragma warning restore 612, 618
        }
    }
}
